### ISSUE TITLE
Unable to use this package

### ISSUE THREAD

**Issue by marpeja** [DLu/tf_transformations#4]

**Comment by marpeja** [comment]
> I am new with ROS, and wanted to use this package for the "introduction to tf2" tutorial of ROS2.
> 
> However, after downloading transforms3d and downloading this package into the src folder of my workspace by using "`git clone https://github.com/DLu/tf_transformations/`" I keep getting
> 
> `ModuleNotFoundError: No module named 'tf_transformations'`
> 
> when calling `ros2 launch turtle_tf2_py turtle_tf2_demo.launch.py` from https://docs.ros.org/en/foxy/Tutorials/Tf2/Introduction-To-Tf2.html tutorial.
> 
> I am looking forward to hearing from you!

**Comment by marpeja** [comment]
I deleted and reinstalled everything and now it works, however, I am not able to control the turtle as mentioned in the tutorial https://docs.ros.org/en/foxy/Tutorials/Tf2/Introduction-To-Tf2.html while when having the `ModuleNotFoundError: No module named 'tf_transformations'` error, I was able to do it although the second turtle didn't follow the first one

**Comment by DLu** [comment]
Hi! Sorry you were having trouble. Best of luck
