### ISSUE TITLE
tf_transformations.euler_from_quaternion() is incorrect. 

### ISSUE THREAD

**Issue by JET00wy** [DLu/tf_transformations#7]
tf_transformations.euler_from_quaternion([0.998, 0.064, 0, 0]) is supposed to return [0.123, 0, 0], but it returned [3.1415926, -0.0, 0.12289]. The angle doesn't work well.

**Comment by DLu** [comment]
That's part of the problem with euler angles isn't it? You can have multiple representations of the same angle that are equivalent. The math seems to [check out here](https://www.andre-gaschler.com/rotationconverter/) for me.

**Comment by JET00wy** [comment]
> That's part of the problem with euler angles isn't it? You can have multiple representations of the same angle that are equivalent. The math seems to [check out here](https://www.andre-gaschler.com/rotationconverter/) for me.

In the given link, it also gives the Euler angle (XYZ as default) of [ x: 0.1280811, y: 0, z: 0], but tf_transformations.euler_from_quaternion([0.998, 0.064, 0, 0]) returns [3.1415926, -0.0, 0.12289], which is wrong.
